export const Constant = {
    API_METHOD: {
        GET_ALL_EMP:'GetAllEmployee',
        GET_ALL_CLIENTS:'GetAllClients'
    },
    VALIDATION_MESSAGE: {
        REQUIRED: 'This field is required',
        INVALID_EMAIL: 'Invalid email',
        INVALID_PHONE: 'Invalid phone number',
        INVALID_PASSWORD: 'Invalid password',
        INVALID_NAME: 'Invalid name',
        INVALID_URL: 'Invalid URL',
        INVALID_NUMBER: 'Invalid number',
        INVALID_DATE: 'Invalid date',
        INVALID_TIME: 'Invalid time',
        INVALID_DATE_TIME: 'Invalid date time',
        INVALID_CURRENCY: 'Invalid currency',
        INVALID_PERCENTAGE: 'Invalid percentage',
        INVALID_LENGTH: 'Invalid length',
        INVALID_MIN_LENGTH: 'Invalid min length',
        INVALID_MAX_LENGTH: 'Invalid max length',
        INVALID_PATTERN: 'Invalid pattern',
        INVALID_MATCH: 'Invalid match',
        INVALID_RANGE: 'Invalid range',
        INVALID_MIN: 'Invalid min',
        INVALID_MAX: 'Invalid max',
        INVALID_GREATER_THAN: 'Invalid greater than',
        INVALID_LESS_THAN: 'Invalid less than',
        INVALID_GREATER_THAN_EQUAL: 'Invalid greater than equal',
        INVALID_LESS_THAN_EQUAL: 'Invalid less than equal',
        INVALID_NOT_EQUAL: 'Invalid not equal',
        INVALID_UNIQUE: 'Invalid unique',
        INVALID_NOT_UNIQUE: 'Invalid not unique',
        INVALID_NOT_FOUND: 'Invalid not found',
        INVALID_ALREADY_EXISTS: 'Invalid already exists',
        INVALID_NOT_EXISTS: 'Invalid not exists',
        INVALID_NOT_MATCH: 'Invalid not match',
        INVALID_NOT_IN: 'Invalid not in',
        INVALID_NOT_EQUAL_TO: 'Invalid not equal to',
        INVALID_NOT_GREATER_THAN: 'Invalid not greater than',
        INVALID_NOT_LESS_THAN: 'Invalid not less than',
        INVALID_NOT_GREATER_THAN_EQUAL: 'Invalid not greater than equal',
        INVALID_NOT_LESS_THAN_EQUAL: 'Invalid not less than equal',
        INVALID_NOT_BETWEEN: 'Invalid not between',
        INVALID_NOT_CONTAIN: 'Invalid not contain',
        INVALID_NOT_START_WITH: 'Invalid not start with',
        INVALID_NOT_END_WITH: 'Invalid not end with',
        INVALID_NOT_UPPERCASE: 'Invalid not uppercase',
        INVALID_NOT_LOWERCASE: 'Invalid not lowercase',
        INVALID_NOT_DIGIT: 'Invalid not digit',
        INVALID_NOT_DECIMAL: 'Invalid not decimal',
        INVALID_NOT_ALPHANUMERIC: 'Invalid not alphanumeric',
        INVALID_NOT_ALPHABET: 'Invalid not alphabet',
        INVALID_NOT_NUMBER: 'Invalid not number',
        INVALID_NOT_STRING: 'Invalid not string',
    }


}
